language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH-TOKEN
  keep_history: true
  on:
    branch: master
