language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn deploy

deploy:
  - provider: pages
    skip_cleanup: true
    secure: "lpHKDBQIWytIC6EYmftd+u7WGABE+FkQ+Oq8Rlak64c5qOKNm8uIaEurRa6VmYRVckqVPRuDqTMM8b0bA3uzymvRxCT+lFmcrS+WqIEn8bP5t6tBSOfUStxir4cOZIyjwmrdKPTFSBU47MpJFCupA932I4LUPmMtvknvs/i8OKTDBZnSYBjHXcsF5F9lpKiId2CyOZGByIkW31fWWzpowlyPywoOsOY684P7lgwkLW6IqYpD5W3kK7Sai8iwQ4MeSHtajgb3KyHulLJlzr4nrjGbAhUKkkKA74Ryg5BBZaUE/cCH+dND/aPDJP3SUjd0ZafUoq3P9Vhj231g4zUi3V5LFwKlDAIek3zIVBTRx6hvo+JCej5OjL+9OTKouw7Kz48Jpk4a1iGJbooRCVSkZwbFz9h2j500RQkdIlLJLqmJhF/ylxFt/dXDv90Bj3aN2zQICueeChmWmDz7Tjzuh2GWESTus4bCTTXlDjzv7PSVO02jrviBwBiQ6KkAumBH+2bQ1Dh11HXzIkGCD3qCFxTL1qpdMmTeZI4wBsw+F36xiGYKMRUNVgKCHHFfNk9WrKiD4TNdEQQfB1mpJEqGyXRjKaf1eI5pGynK5HDUOWMEhELVBm5dCkU092AEk+C1wcT7bNZY//bevPkMsoxamq4L+/zXC08JAzve64UNVVo="
    keep_history: true
    on:
      branch: master
